name: CI

on:
  push:
    branches: [main]

env:
  fennel-version: 0.10.0
  lua-version: luajit-2.1.0-beta3
  binary-path: ${{ github.workspace }}/.bin

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare Lua
        uses: leafo/gh-actions-lua@master # Avoid compile
        with:
          luaVersion: ${{ env.lua-version }}

      - name: Add PATH and move lua binary to PATH
        run: |
          mkdir -p ${{ env.binary-path }}
          cp .lua/bin/* ${{ env.binary-path }}
          echo "${{ env.binary-path }}" >> $GITHUB_PATH

      - name: Prepare Fennel
        run: |
          git clone https://github.com/bakpakin/Fennel.git
          cd Fennel && git checkout ${{ env.fennel-version }}
          make fennel
          mkdir -p ${{ env.binary-path }}
          cp fennel ${{ env.binary-path }}

      - name: Cache Lua and Fennel
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-dependencies-${{ env.fennel-version }}-${{ env.lua-version }}
          path: ${{ env.binary-path }}

      - name: Run test
        run: |
          cd test
          fennel tests.fnl

  lua-docs:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Restore fennel cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-dependencies-${{ env.fennel-version }}-${{ env.lua-version }}
          path: ${{ env.binary-path }}

      - name: Update PATH
        run: |
          echo "${{ env.binary-path }}" >> $GITHUB_PATH

      - name: Update Lua source
        run: |
          mkdir -p lua
          mkdir -p lua/fulib
          fennel -c fnl/fulib/init.fnl > lua/fulib/init.lua

      - name: Update docs
        run: |
          sudo apt install -y pandoc
          cat fnl/fulib/init.fnl | fennel scripts/doc.fnl | pandoc -t markdown > docs.md

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[Bot] Update lua source and docs"
          commit_author: Github Action <actions@github.com>
          file_pattern: lua docs.md
