name: CI

on:
  push:
    branches: [main]

env:
  fennel-version: 1.1.0
  lua-version: luajit-2.1.0-beta3
  binary-path: ${{ github.workspace }}/.bin

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare Lua
        uses: leafo/gh-actions-lua@master # Avoid compile
        with:
          luaVersion: ${{ env.lua-version }}

      - name: Add PATH and move lua binary to PATH
        run: |
          mkdir -p ${{ env.binary-path }}
          cp .lua/bin/* ${{ env.binary-path }}
          echo "${{ env.binary-path }}" >> $GITHUB_PATH

      - name: Prepare Fennel
        run: |
          git clone https://github.com/bakpakin/Fennel.git
          cd Fennel && git checkout ${{ env.fennel-version }}
          make fennel
          mkdir -p ${{ env.binary-path }}
          cp fennel ${{ env.binary-path }}

      - name: Cache Lua and Fennel
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-dependencies-${{ env.fennel-version }}-${{ env.lua-version }}
          path: ${{ env.binary-path }}

      - name: Run test
        run: |
          cd test
          fennel tests.fnl

