name: CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare Lua
        uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: luajit-2.1.0-beta3

      - name: Prepare Fennel
        run: |
          git clone https://github.com/bakpakin/Fennel.git
          cd Fennel && git checkout 0.10.0
          make fennel
          cp fennel /usr/local/bin

      - name: Run test
        run: |
          cd test
          fennel tests.fnl
