name: CI

on:
  push:
    branches: [main]

env:
  fennel-version: 0.10.0
  lua-version: luajit-2.1.0-beta3
  binary-path: ${GITHUB_WORKSPACE}/.bin

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare Lua
        uses: leafo/gh-actions-lua@master # Avoid compile
        with:
          luaVersion: ${{ env.lua-version }}

      - name: Prepare Fennel
        run: |
          git clone https://github.com/bakpakin/Fennel.git
          cd Fennel && git checkout ${{ env.fennel-version }}
          make fennel
          cp fennel ${{ env.binary-path }}

      - name: Cache Lua and Fennel
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-dep-${{ env.fennel-version }}-${{ env.lua-version }}
          path: ${{ env.binary-path }}

      - name: Update PATH
        run: echo ${{ env.binary-path }} >> $GITHUB_PATH

      - name: Run test
        run: |
          cd test
          fennel tests.fnl

  lua-gen:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Restore fennel cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-dep-${{ env.fennel-version }}-${{ env.lua-version }}
          path: ${{ env.binary-path }}

      - name: Update Lua source
        run: |
          mkdir -p lua
          mkdir -p lua/fulib
          fennel -c fnl/fulib/init.fnl > lua/fulib/init.lua

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[lua-gen] Update lua source"
          file_pattern: lua
